/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValvetRouteImport } from './routes/valvet'
import { Route as InkorgenRouteImport } from './routes/inkorgen'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicTriggerRouteImport } from './routes/api/public/trigger'
import { Route as ApiPublicSceneRouteImport } from './routes/api/public/scene'
import { Route as ApiPublicCinemaBrainRouteImport } from './routes/api/public/cinema-brain'

const ValvetRoute = ValvetRouteImport.update({
  id: '/valvet',
  path: '/valvet',
  getParentRoute: () => rootRouteImport,
} as any)
const InkorgenRoute = InkorgenRouteImport.update({
  id: '/inkorgen',
  path: '/inkorgen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTriggerRoute = ApiPublicTriggerRouteImport.update({
  id: '/api/public/trigger',
  path: '/api/public/trigger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSceneRoute = ApiPublicSceneRouteImport.update({
  id: '/api/public/scene',
  path: '/api/public/scene',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCinemaBrainRoute = ApiPublicCinemaBrainRouteImport.update({
  id: '/api/public/cinema-brain',
  path: '/api/public/cinema-brain',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inkorgen': typeof InkorgenRoute
  '/valvet': typeof ValvetRoute
  '/api/public/cinema-brain': typeof ApiPublicCinemaBrainRoute
  '/api/public/scene': typeof ApiPublicSceneRoute
  '/api/public/trigger': typeof ApiPublicTriggerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inkorgen': typeof InkorgenRoute
  '/valvet': typeof ValvetRoute
  '/api/public/cinema-brain': typeof ApiPublicCinemaBrainRoute
  '/api/public/scene': typeof ApiPublicSceneRoute
  '/api/public/trigger': typeof ApiPublicTriggerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inkorgen': typeof InkorgenRoute
  '/valvet': typeof ValvetRoute
  '/api/public/cinema-brain': typeof ApiPublicCinemaBrainRoute
  '/api/public/scene': typeof ApiPublicSceneRoute
  '/api/public/trigger': typeof ApiPublicTriggerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inkorgen'
    | '/valvet'
    | '/api/public/cinema-brain'
    | '/api/public/scene'
    | '/api/public/trigger'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inkorgen'
    | '/valvet'
    | '/api/public/cinema-brain'
    | '/api/public/scene'
    | '/api/public/trigger'
  id:
    | '__root__'
    | '/'
    | '/inkorgen'
    | '/valvet'
    | '/api/public/cinema-brain'
    | '/api/public/scene'
    | '/api/public/trigger'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InkorgenRoute: typeof InkorgenRoute
  ValvetRoute: typeof ValvetRoute
  ApiPublicCinemaBrainRoute: typeof ApiPublicCinemaBrainRoute
  ApiPublicSceneRoute: typeof ApiPublicSceneRoute
  ApiPublicTriggerRoute: typeof ApiPublicTriggerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/valvet': {
      id: '/valvet'
      path: '/valvet'
      fullPath: '/valvet'
      preLoaderRoute: typeof ValvetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inkorgen': {
      id: '/inkorgen'
      path: '/inkorgen'
      fullPath: '/inkorgen'
      preLoaderRoute: typeof InkorgenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/trigger': {
      id: '/api/public/trigger'
      path: '/api/public/trigger'
      fullPath: '/api/public/trigger'
      preLoaderRoute: typeof ApiPublicTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scene': {
      id: '/api/public/scene'
      path: '/api/public/scene'
      fullPath: '/api/public/scene'
      preLoaderRoute: typeof ApiPublicSceneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cinema-brain': {
      id: '/api/public/cinema-brain'
      path: '/api/public/cinema-brain'
      fullPath: '/api/public/cinema-brain'
      preLoaderRoute: typeof ApiPublicCinemaBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InkorgenRoute: InkorgenRoute,
  ValvetRoute: ValvetRoute,
  ApiPublicCinemaBrainRoute: ApiPublicCinemaBrainRoute,
  ApiPublicSceneRoute: ApiPublicSceneRoute,
  ApiPublicTriggerRoute: ApiPublicTriggerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
