/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicTriggerRouteImport } from './routes/api/public/trigger'
import { Route as ApiPublicCinemaBrainRouteImport } from './routes/api/public/cinema-brain'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTriggerRoute = ApiPublicTriggerRouteImport.update({
  id: '/api/public/trigger',
  path: '/api/public/trigger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCinemaBrainRoute = ApiPublicCinemaBrainRouteImport.update({
  id: '/api/public/cinema-brain',
  path: '/api/public/cinema-brain',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/cinema-brain': typeof ApiPublicCinemaBrainRoute
  '/api/public/trigger': typeof ApiPublicTriggerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/cinema-brain': typeof ApiPublicCinemaBrainRoute
  '/api/public/trigger': typeof ApiPublicTriggerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/cinema-brain': typeof ApiPublicCinemaBrainRoute
  '/api/public/trigger': typeof ApiPublicTriggerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/cinema-brain' | '/api/public/trigger'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/cinema-brain' | '/api/public/trigger'
  id: '__root__' | '/' | '/api/public/cinema-brain' | '/api/public/trigger'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicCinemaBrainRoute: typeof ApiPublicCinemaBrainRoute
  ApiPublicTriggerRoute: typeof ApiPublicTriggerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/trigger': {
      id: '/api/public/trigger'
      path: '/api/public/trigger'
      fullPath: '/api/public/trigger'
      preLoaderRoute: typeof ApiPublicTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cinema-brain': {
      id: '/api/public/cinema-brain'
      path: '/api/public/cinema-brain'
      fullPath: '/api/public/cinema-brain'
      preLoaderRoute: typeof ApiPublicCinemaBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicCinemaBrainRoute: ApiPublicCinemaBrainRoute,
  ApiPublicTriggerRoute: ApiPublicTriggerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
